// app/ui/langs.js
export const en = {
  appName: "Ravchamo",
  tagline: "what should I eat?",
  location: "Location",
  loc: {
    ready: "Location ready",
    getting: "Getting location...",
    deniedVake: "Permission denied — using Vake center.",
  },
  setLocation: "Set my location...",
  budget: "Select a budget",
  low: "Low",
  medium: "Medium",
  high: "High",
  cravings: "Pick cravings (optional)",
  dietary: "Dietary preferences (exclude)",
  exclude: "I don't want (exclude)",
  time: "Time",
  fast: "Fast",
  relaxed: "Relaxed",
  openNow: "Open now",
  findDishes: "Show options",
  seeResults: "Show results",
  lucky: "I'm feeling lucky",
  resultsTop: "Top picks",
  noMatches: "No matches yet. Try fewer filters.",
  call: "Call",
  openInMaps: "Open in Maps",
  gel: "GEL",
  back: "Back to results",
disclaimer: "Menu data may be inaccurate. Always check with the restaurant about allergens and availability.",

  tags: {
    // cravings
    georgian: "Georgian",
    grill: "Grill",
    wrap: "Wrap",
    sushi: "Sushi",
    pizza: "Pizza",
    salad: "Salad",
    soup: "Soup",
    vegan: "Vegan",
    healthy: "Healthy",
    cheesy: "Cheesy",
    spicy: "Spicy",

    // dietary/exclude
    pork: "Pork",
    beef: "Beef",
    chicken: "Chicken",
    fish: "Fish",
    gluten: "Gluten",
    dairy: "Dairy",
    halal: "Halal",
    vegetarian: "Vegetarian",
  },
};

export const ka = {
  appName: "რა ვჭამო?",
  tagline: "რას ვჭამო?",
  location: "ადგილმდებარეობა",
  loc: {
    ready: "ლოკაცია მზად არის",
    getting: "ლოკაცია იტვირთება...",
    deniedVake: "უფლება არ არის — ვაკის ცენტრს ვიყენებთ.",
  },
  setLocation: "ჩემი ლოკაცია...",
  budget: "აირჩიე ბიუჯეტი",
  low: "დაბალი",
  medium: "საშუალო",
  high: "მაღალი",
  cravings: "რა გაგისწორდება (არასავალდებულო)",
  dietary: "დიეტური შეზღუდვები (გამორიცხვა)",
  exclude: "რა არ გაგისწორდება (გამორიცხვა)",
  time: "დრო",
  fast: "სწრაფად",
  relaxed: "მშვიდად",
  openNow: "ახლა ღიაა",
  findDishes: "მაჩვენე არჩევანი",
  seeResults: "მაჩვენე შედეგები",
  lucky: "იღბლიან რეჟიმში",
  resultsTop: "საუკეთესო ვარიანტები",
  noMatches: "შედეგი ვერ მოიძებნა. სცადე ნაკლები ფილტრი.",
  call: "დარეკვა",
  openInMaps: "გახსენი რუკაზე",
  gel: "₾",
  openInMaps: "გახსენი რუკაზე",
gel: "₾",

back: "უკან დაბრუნება",
disclaimer: "მენიუს მონაცემები შესაძლოა არ იყოს ზუსტი. ინფორმაცია ალერგენებსა და ხელმისაწვდომობაზე გადაამოწმეთ რესტორანთან.",

tags: {

  tags: {
    // cravings
    georgian: "ქართული",
    grill: "გრილი",
    wrap: "როლი/რეხვრეპი",
    sushi: "სუში",
    pizza: "პიცა",
    salad: "სალათი",
    soup: "სუპი",
    vegan: "ვეგანი",
    healthy: "ჯანსაღი",
    cheesy: "ყველიანი",
    spicy: "ცხარე",

    // dietary/exclude
    pork: "ღორის",
    beef: "საქონლის",
    chicken: "ქათმის",
    fish: "თევზი",
    gluten: "გლუტენი",
    dairy: "რძის პროდუქტები",
    halal: "ჰალალი",
    vegetarian: "ვეგეტარიანული",
  },
};
