// app/ui/langs.js
export const en = {
  appName: "Ravchamo",
  tagline: "what should I eat?",
  location: "Location",
  setLocation: "Set my location...",
  budget: "Select a budget",
  low: "Low",
  medium: "Medium",
  high: "High",
  cravings: "Pick cravings (optional)",
  exclude: "I don't want (exclude)",
  time: "Time",
  openNow: "Open now",
  findDishes: "Show options",
  lucky: "I'm feeling lucky",
  resultsTop: "Top picks",
  noMatches: "No matches yet. Try fewer filters.",
  call: "Call",
  openInMaps: "Open in Maps",
  gel: "GEL",
  tags: {
    georgian: "Georgian",
    khinkali: "Khinkali",
    bbq: "BBQ",
    veg: "Vegetarian",
    vegan: "Vegan",
    spicy: "Spicy",
    dessert: "Dessert",
    pizza: "Pizza",
    salad: "Salad",
    soup: "Soup",
    seafood: "Seafood",
    fast: "Fast",
    slow: "Slow",
  },
};

export const ka = {
  appName: "რა ვჭამო?",
  tagline: "რას ვჭამო?",
  location: "ადგილმდებარეობა",
  setLocation: "ჩემი ლოკაცია...",
  budget: "აირჩიე ბიუჯეტი",
  low: "დაბალი",
  medium: "საშუალო",
  high: "მაღალი",
  cravings: "ეხა რა გაგისწორდებოდა (არასავალდებულო)",
  exclude: "რა არ გინდა (გამორიცხვა)",
  time: "დრო",
  openNow: "ახლა ღიაა",
  findDishes: "მაჩვენე არჩევანი",
  lucky: "დამირენდომე",
  resultsTop: "საუკეთესო ვარიანტები",
  noMatches: "შედეგი ვერ მოიძებნა. სცადე ნაკლები ფილტრი.",
  call: "დარეკვა",
  openInMaps: "რუკაზე გახსნა",
  gel: "₾",
  tags: {
    georgian: "ქართული",
    khinkali: "ხინკალი",
    bbq: "ბარბექიუ",
    veg: "ვეგეტარიანული",
    vegan: "ვეგანი",
    spicy: "ცხარე",
    dessert: "დესერტი",
    pizza: "პიცა",
    salad: "სალათი",
    soup: "სუპი",
    seafood: "ზღვის პროდუქტები",
    fast: "სწრაფად",
    slow: "მოვითმენ",
  },
};
