export const STR = {
  appName: "Ravchamo",
  tagline: "What should I eat?",
  start: "Start",
  useMyLocation: "Use my location",
  or: "or",
  selectBudget: "Select a budget",
  priceLow: "₾ Low",
  priceMed: "₾₾ Medium",
  priceHigh: "₾₾₾ High",
  cravings: "Pick cravings (optional)",
  dietary: "I don't want (exclude)",
  time: "Time",
  fast: "Fast",
  relaxed: "Relaxed",
  seeResults: "See results",
  feelingLucky: "I'm feeling lucky",
  distance: "Distance",
  openNow: "Open now",
  details: "Details",
  back: "Back",
  call: "Call",
  map: "Open in Maps",
  price: "Price",
  tags: "Tags",
  about: "About",
  disclaimer: "Menu data may be inaccurate. Always check with the restaurant about allergens and availability."
};
