-- =============================================================================
-- recommend_dishes v3 — make craving filter truly optional
-- Apply via Supabase SQL Editor. Project ref: mmyxzagdcwnjjoowufiu
-- =============================================================================
--
-- Context: cravings (categories) are now an optional input on the home page.
-- The user can search with just budget + vibe. The RPC must therefore treat
-- an empty `craving_categories` array as "no category filter."
--
-- Single surgical change to the existing function:
--
--   Inside the `scored` CTE WHERE clause, find the current category filter
--   (likely something like `d.category = any(craving_categories)` or a more
--   elaborate scoring expression that hard-requires a category match).
--
--   Replace it so that an empty array skips the filter entirely:
--
--       and (
--         array_length(craving_categories, 1) is null
--         or d.category = any(craving_categories)
--       )
--
--   If the original logic *scores* a category match (e.g. boosts dishes whose
--   category is in the list) rather than *filtering*, the change is simpler:
--   leave the scoring expression alone — an empty array just contributes zero
--   boost, which is the desired "no preference" behavior. In that case the
--   only thing to verify is that there is no hard `WHERE` filter that rejects
--   rows when the array is empty.
--
-- Everything else stays identical (jitter, exclude list, restaurant
-- diversification, LIMIT 10, return columns, grants).
--
-- ── How to apply ─────────────────────────────────────────────────────────────
-- 1. In Supabase SQL Editor, fetch the current definition:
--
--      select pg_get_functiondef(p.oid)
--      from pg_proc p
--      join pg_namespace n on n.oid = p.pronamespace
--      where n.nspname = 'public' and p.proname = 'recommend_dishes';
--
-- 2. Find the WHERE clause inside the `scored` CTE.
--
-- 3. If there's a hard category filter, wrap it with the
--    `array_length(...) is null OR ...` guard shown above.
--
-- 4. Re-run the modified CREATE OR REPLACE FUNCTION.
--
-- ── Smoke test ───────────────────────────────────────────────────────────────
-- Confirm both shapes work and return non-empty results:
--
--   -- with cravings (should match v2 behavior)
--   SELECT count(*) FROM recommend_dishes(
--     41.71, 44.77, 'med', ARRAY['georgian']::text[], 'I''m on a hangover'
--   );
--
--   -- WITHOUT cravings (new: must also return results)
--   SELECT count(*) FROM recommend_dishes(
--     41.71, 44.77, 'med', ARRAY[]::text[], 'I''m on a hangover'
--   );
--
-- Both should return up to 10. The "no cravings" call should be a strict
-- superset of the "with cravings" call (no category restriction).
-- =============================================================================
